idf_component_register(
    SRCS
        "main.cpp"
        "board_page.cpp"
        "board_snapshot.cpp"
        "board_server.cpp"
        "chess_board.cpp"
        "chess_game.cpp"
        "game.cpp"
        "numpad.cpp"
        "led.cpp"
        "standard_output.cpp"
        "wifi_access_point.cpp"
    INCLUDE_DIRS "."
    REQUIRES
        esp_driver_gpio
        esp_event
        esp_http_server
        esp_netif
        esp_wifi
        nvs_flash
)
