idf_component_register(
    SRCS
        "main.cpp"
        "game_logic/chess_board.cpp"
        "game_logic/chess_game.cpp"
        "game_logic/chess_notation.cpp"
        "game_logic/chess_rules.cpp"
        "game_logic/game.cpp"
        "game_logic/pieces/piece.cpp"
        "game_logic/pieces/pawn.cpp"
        "game_logic/pieces/knight.cpp"
        "game_logic/pieces/bishop.cpp"
        "game_logic/pieces/rook.cpp"
        "game_logic/pieces/queen.cpp"
        "game_logic/pieces/king.cpp"
        "peripherals/led.cpp"
        "peripherals/numpad.cpp"
        "peripherals/standard_output.cpp"
        "server/board_page.cpp"
        "server/board_snapshot.cpp"
        "server/board_server.cpp"
        "server/wifi_access_point.cpp"
    INCLUDE_DIRS
        "."
        "game_logic"
        "game_logic/pieces"
        "peripherals"
        "server"
    REQUIRES
        esp_driver_gpio
        esp_event
        esp_http_server
        esp_netif
        esp_wifi
        nvs_flash
)
